version: 2

mkdocs:
  configuration: docs/book.toml
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install mdbook==0.4.28

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  fail_on_warning: false