name: MDBook Documentation (Archived)

# This workflow is archived since we now use ReadTheDocs.
# It is kept for reference purposes only and does not run automatically.

on:
  # Disabled automatic triggers
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.28'

      - name: Build Documentation
        run: mdbook build docs

      - name: Verify Documentation
        run: |
          echo "Checking generated documentation..."
          echo "Main directory:"
          ls -la docs/book/
          echo "Doc structure and roadmap:"
          ls -la docs/book/ROADMAP.html || echo "ROADMAP.html not found in expected location"
          echo "Getting started section:"
          ls -la docs/book/getting-started/
          echo "Index file header:"
          cat docs/book/index.html | head -30
          echo "Checking links in SUMMARY.html:"
          grep -o '<a href="[^"]*"' docs/book/SUMMARY.html || echo "No links found in SUMMARY.html"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          force_orphan: true
          cname: docs.pathmaster.dev