name: Validate Documentation

on:
  push:
    branches:
      - main
      - feature/go-migration
    paths:
      - 'docs/**'
      - '.readthedocs.yml'
  workflow_dispatch:

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Check Sphinx build
        run: |
          sphinx-build -b html docs docs/_build/html
          echo "Documentation build successful"